### ISSUE TITLE
Decide about how to handle static nested classes and implement it

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#69] opened 2015-12-16 20:29 UTC
@bechte brought this up in our last Skype call.

```java
class Foo {
    class Bar {
    }
}
```

should be handled differently than

```java
class Foo {
    static class Bar {
    }
}
```

---

- [x] Introduce test that checks that private static nested classes are not discovered via classpath scanning but non-private static nested classes are.

**Comment by jlink** [comment] 2015-12-16 21:05
Any reason/arguments to handle it differently than in the prototype?

First example wouldn't do anything unless Bar is annotated with @Nested.
Second example is just two different classes. Bar has a different naming
scope. Seems as consistent as we can get.

What would be the alternative?

Johannes


2015-12-16 21:52 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-17 07:28
@marcphilipp: Thanks for opening this issue, I totally forgot it. Sorry.

Quote from: http://docs.oracle.com/javase/tutorial/java/javaOO/nested.html
> Terminology: Nested classes are divided into two categories: static and non-static. Nested classes that are declared static are simply called static nested classes. Non-static nested classes are called inner classes.

In this manner, we might also rethink about the `@Nested` as it conflicts with the definition from the tutorial.

Anyways, reasons for changing the behavior:
* A nested member class has full access to all the members of the enclosing class. It should be a child of the enclosed class running all the before/after methods consequently. We have the restriction that we only add nested member classes if they are annotated with `@Nested`. This give a flexibility that we should keep. Still we should think about renaming the annotation, maybe `@NestedTests`?
* A nested static class has no access to member of its enclosing class. Therefore, we must not execute the beforeEach/afterEach methods of the enclosing class. As we execute them on the class level, a logical consequence is, that we put nested static class on the same level as their enclosing class. However, this also excludes beforeAll/afterAll methods from being executed which might not be our final goal. Having a special behavior for those classes, we could handle it and call the beforeAll/afterAll methods again.
* Keeping the nested static class within the hierarchy of the enclosed class, the enclosed class' `ClassTestDescriptor` would need to react on the child type and handle the static nested class children differently. I don't like having the `ClassTestDescriptor` to care about the type of its children.

Therefore, I think we should investigate some time in changing it. I already have done this in my feature branch for #29. We could also introduce it within master.

**Comment by jlink** [comment] 2015-12-17 07:37
Reading your points you seem to argue for the way we're already doing it,
that is
- Nest test cases (with before/afterEach semantics) only if they are
annotated and non static
- Treating static nesting as namespace only
And yet you say "I already have done this in my feature branch". Could you
shortly explain how your branch behaves differently compared to master in
that respect?


2015-12-17 8:28 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-17 08:10
Example taken from `NestedTestClassesTests`:
https://github.com/junit-team/junit-lambda/blob/feature-29-extensible-discovery/junit-tests/src/test/java/org/junit/gen5/engine/junit5/NestedTestClassesTests.java

```
public class NestedTestClassesTests ... {
  private static class TestCaseWithNesting {
    ...
  }
}
```

A) The resulting tree for treating nested static classes and nested member classes would be:
- EngineTestDescriptor (for JUnit5TestEngine)
-- ClassTestDescriptor (for NestedTestClassesTests)
--- ClassTestDescriptor (for TestCaseWithNesting)

B) The resulting tree for treating nested static classes differently as proposed here would be:
- EngineTestDescriptor (for JUnit5TestEngine)
-- ClassTestDescriptor (for NestedTestClassesTests)
-- ClassTestDescriptor (for TestCaseWithNesting)

While NestedTestClassesTests does not contain JUnit5 tests, it will be pruned from the tree.

We discussed this in the Skype call on Tuesday, and we were discussion pro B. That's why I introduced this behavior in my feature branch, already. I did not say we need to do this because I already did it, but I wanted to mention that, so that we have this in mind and not doing things twice. ;-)

**Comment by jlink** [comment] 2015-12-17 08:41
I'm slow on the uptake today, sorry. Have to ask again:


2015-12-17 9:10 GMT+01:00 Stefan Bechtold <notifications@github.com>:

>
> B) The resulting tree for treating nested static classes differently as
> proposed here would be:
>
>    - EngineTestDescriptor (for JUnit5TestEngine) -- ClassTestDescriptor
>    (for NestedTestClassesTests) -- ClassTestDescriptor (for
>    TestCaseWithNesting)
>
> While NestedTestClassesTests does not contain JUnit5 tests, it will be
> pruned from the tree.
>

You are pruning a node INBETWEEN two other nodes so that
EngineTestDescriptor (for JUnit5TestEngine) will have ClassTestDescriptor
(for TestCaseWithNesting) as a direct child?

Could NestedTestClassesTests have before/afterAll methods that will be
applied for tests in TestCaseWithNesting?

**Comment by bechte** [comment] 2015-12-17 10:08
We won't prune intermediate nodes from the tree. The pruning is just a consequence in this specific example. If the `NestedTestClassesTests` has more children than the `ClassTestDescriptor` for `TestCaseWithNesting` it needs to stay and will not be pruned from the tree.

Pulling nested static classes outside the enclosed class should be done during the test discovery, i.e. finding a nested static class we create a `TestDescriptor` for it and could attach it to the grand-father node (parent of parent) instead of attaching it to the parent (the enclosing class) directly. That's the core difference/idea.

As a consequence, it is not obvious (from the tree) that beforeAll/afterAll from the enclosing class will get executed. Our current execution model would also not execute them, as they do not belong to the tree.

As already mentioned:
> However, this also excludes beforeAll/afterAll methods from being executed which might not be our final goal. Having a special behavior for those classes, we could handle it and call the beforeAll/afterAll methods again.

We need to discuss this point. I could live with it. I never use inner static classes in tests to describe tests (only for creating stubs, etc.), but there could be people who want to use this feature. Clearly, (context/nested) hierarchies built of static classes are very different from (context/nested) hierarchies built of member classes, as described in my first comment.

**Comment by jlink** [comment] 2015-12-17 10:37
I hopefully get it now:
Inner static classes should automatically been executed when their parent
is used in ClassSpecification, but their outside class should not become a
parent in the descriptor hierarchy.

Is that your suggestion? If so, it sounds reasonable.


2015-12-17 11:08 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-17 11:27
Absolutely. The discovery should find the nested static classes, but we would place it outside of the enclosed class in the tree, just as you described it.

Still, we have to decide on the "beforeAll/afterAll" behavior: What is the expected behavior? For the moment, I think not to run them is okay (at least from a tree perspective). Since they will become a somehow own kind of `TestDescriptor` we still can decide on this later on.

**Comment by jlink** [comment] 2015-12-17 15:35
If there is no veto on collecting all static subclasses of a test class as
well, I'll put that functionality into master as well.

Anyone?

2015-12-17 12:27 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-17 15:58
What happens to double nested (or even deeper) static classes? shall they also be pull up?

do we have a decision about handling of beforeAll / afterAll methods?

Shall we clarify this next Tuesday in the Skype call before changing to master.

Anyways, I could live with it for now. 

Stefan

**Comment by jlink** [comment] 2015-12-17 16:13
OK. Let's wait till Tuesday then.

2015-12-17 16:59 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-17 20:38
Just found one more quote on the Java Tutorial (http://docs.oracle.com/javase/tutorial/java/javaOO/nested.html) which might guide us as well:

> Note: A static nested class interacts with the instance members of its outer class (and other classes) just like any other top-level class. In effect, a static nested class is behaviorally a top-level class that has been nested in another top-level class for packaging convenience.

In this manner Tests in such a static nested class should have nothing in common with its enclosed class, but really behave like any other top level class.

My proposal for the discussion on Tuesday:
* Treat nested static classes like top-level classes
* Pull them up onto the level of the top-level class such that: `enclosedClassTestDescriptor.getParent() == nestedStaticClassTestDescriptor.getParent()` evaluate to true.
* Repeat this for double (and even more) nested static classes

Example:

```java
public class TopLevelTestCase {
  public static NestedStaticClassTestCase {
    public static DoubleNestedStaticClassTestCase {
      public static ThreeTimesNestedStaticClassTestCase {
        // ... test go here and there
      }
    }
  }
}
````

The resulting test descriptor tree of executing the TestPlan for `TopLevelTestCase` would be:

- `ClassTestDescriptor` for `TopLevelTestCase`
  - tests within `TopLevelTestCase` ...
- `NestedStaticClassTestDescriptor` for `TopLevelTestCase.NestedStaticClassTestCase`
  - tests within `TopLevelTestCase.NestedStaticClassTestCase` ...
- `NestedStaticClassTestDescriptor` for `TopLevelTestCase.NestedStaticClassTestCase.DoubleNestedStaticClassTestCase`
  - tests within ...
- `NestedStaticClassTestDescriptor` for `TopLevelTestCase.NestedStaticClassTestCase.DoubleNestedStaticClassTestCase.ThreeTimesNestedStaticClassTestCase`
  - tests within ...

Note: `NestedStaticClassTestDescriptor` is just a placeholder name.

**Comment by jlink** [comment] 2015-12-18 07:44
Is NestedStaticClassTestDescripto needed then? Since the behaviour should
be the same for top level classes and nested static classes,
ClassTestDescriptor might suffice.

2015-12-17 21:38 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment] 2015-12-18 08:24
Yes, that might be the outcome. If it is sufficient then we should definitely use `ClassTestDescriptor` in both cases. :ok_hand:

**Comment by marcphilipp** [comment] 2016-01-11 14:46
## Ideas

still not satisfied with the names

`Bar` is not discovered, it cannot be run:
```java
class Foo {
    class Bar {
        @Test void test() {}
    }
}
```

`Bar` is run as a nested test inside the container `Foo`'s context:
```java
class Foo {
    @Nested class Bar {
        @Test void test() {}
    }
}
```

`Bar` is run as if it were a top-level class:
```java
class Foo {
    @Enclosed static class Bar {
        @Test void test() {}
    }
}
```

**Comment by marcphilipp** [comment] 2016-01-11 15:12
Team decision: Static nested classes are discovered only via classpath scanning if they are not private. There's already `@Nested` for running non-static nested classes inside the containing class' context.

**Comment by jlink** [comment] 2016-01-11 17:13
Fixed in https://github.com/junit-team/junit-lambda/commit/b8c0c3d3a12fd8e072b2c148856ab23650f0f9b4

**Closed by jlink** 2016-01-11 17:13 UTC
